import type { User, Video } from "./types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "creator@aiarklive.com",
    username: "Aphesis21",
    avatar_url: null,
    bio: "Suno + Kling으로 수면음악 AI 영상을 만듭니다.",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "user-2",
    email: "nova@aiarklive.com",
    username: "NovaFrames",
    avatar_url: null,
    bio: "Runway Gen-3 실험영상 크리에이터",
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "user-3",
    email: "loop@aiarklive.com",
    username: "LoopLab",
    avatar_url: null,
    bio: "루프 영상 · ambient AI 비주얼",
    created_at: "2026-03-10T00:00:00Z",
  },
];

export const mockVideos: Video[] = [
  {
    id: "vid-1",
    user_id: "user-1",
    title: "Midnight Rain — AI Lo-fi Sleep Visual",
    description: "Suno로 만든 수면음악과 Kling 비주얼의 조합",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["suno", "kling"],
    genre: "music-video",
    prompt: "rainy window at night, soft neon glow, lo-fi aesthetic, slow camera drift",
    likes_count: 1284,
    views_count: 8420,
    is_nsfw: false,
    created_at: "2026-05-01T10:00:00Z",
  },
  {
    id: "vid-2",
    user_id: "user-2",
    title: "Neon Alley — Cyberpunk Short Film",
    description: "Runway Gen-3로 제작한 30초 단편",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["runway"],
    genre: "short-film",
    prompt: "cyberpunk alley, rain reflections, cinematic tracking shot",
    likes_count: 956,
    views_count: 5210,
    is_nsfw: false,
    created_at: "2026-05-10T14:30:00Z",
  },
  {
    id: "vid-3",
    user_id: "user-3",
    title: "Infinite Ocean Loop",
    description: "Pika + LTX-Video 루프 애니메이션",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["pika", "ltx-video"],
    genre: "loop",
    prompt: null,
    likes_count: 742,
    views_count: 3890,
    is_nsfw: false,
    created_at: "2026-05-15T09:00:00Z",
  },
  {
    id: "vid-4",
    user_id: "user-1",
    title: "AI Sneaker Ad — 15s Spot",
    description: "광고 대행 레퍼런스용 AI 스포츠웨어 광고",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["veo", "runway"],
    genre: "ad",
    prompt: "dynamic product shot, sneaker floating, studio lighting, slow motion",
    likes_count: 612,
    views_count: 4100,
    is_nsfw: false,
    created_at: "2026-05-18T16:00:00Z",
  },
  {
    id: "vid-5",
    user_id: "user-2",
    title: "Abstract Dreams — Experimental",
    description: "Grok + Hailuo 실험 영상",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["grok", "hailuo"],
    genre: "experimental",
    prompt: "surreal morphing shapes, dreamlike colors, non-linear narrative",
    likes_count: 489,
    views_count: 2750,
    is_nsfw: false,
    created_at: "2026-05-20T11:00:00Z",
  },
  {
    id: "vid-6",
    user_id: "user-3",
    title: "Pixel Forest Animation",
    description: "PixVerse 애니메이션 숏폼",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["pixverse"],
    genre: "animation",
    prompt: "pixel art forest, fireflies, gentle wind animation",
    likes_count: 334,
    views_count: 1920,
    is_nsfw: false,
    created_at: "2026-05-21T08:00:00Z",
  },
];

export function attachUsersToVideos(videos: Video[], users: User[]): Video[] {
  const userMap = new Map(users.map((u) => [u.id, u]));
  return videos.map((v) => ({ ...v, user: userMap.get(v.user_id) }));
}
