import type { Challenge, Comment, User, Video } from "./types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "creator@aiarklive.com",
    username: "Aphesis21",
    avatar_url: null,
    bio: "Creating AI sleep music videos with Suno + Kling.",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "user-2",
    email: "nova@aiarklive.com",
    username: "NovaFrames",
    avatar_url: null,
    bio: "Runway Gen-3 experimental film creator",
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "user-3",
    email: "loop@aiarklive.com",
    username: "LoopLab",
    avatar_url: null,
    bio: "Loop videos · ambient AI visuals",
    created_at: "2026-03-10T00:00:00Z",
  },
];

export const mockVideos: Video[] = [
  {
    id: "vid-1",
    user_id: "user-1",
    title: "Midnight Rain — AI Lo-fi Sleep Visual",
    description: "Sleep music made with Suno paired with Kling visuals",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    source_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["suno", "kling"],
    genre: "music-video",
    prompt: "rainy window at night, soft neon glow, lo-fi aesthetic, slow camera drift",
    likes_count: 1284,
    views_count: 8420,
    downloads_count: 312,
    is_nsfw: false,
    created_at: "2026-05-01T10:00:00Z",
  },
  {
    id: "vid-2",
    user_id: "user-2",
    title: "Neon Alley — Cyberpunk Short Film",
    description: "30-second short film made with Runway Gen-3",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    source_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["runway"],
    genre: "short-film",
    prompt: "cyberpunk alley, rain reflections, cinematic tracking shot",
    likes_count: 956,
    views_count: 5210,
    downloads_count: 189,
    is_nsfw: false,
    created_at: "2026-05-10T14:30:00Z",
  },
  {
    id: "vid-3",
    user_id: "user-3",
    title: "Infinite Ocean Loop",
    description: "Loop animation with Pika + LTX-Video",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    source_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["pika", "ltx-video"],
    genre: "loop",
    prompt: null,
    likes_count: 742,
    views_count: 3890,
    downloads_count: 245,
    is_nsfw: false,
    created_at: "2026-05-15T09:00:00Z",
  },
  {
    id: "vid-4",
    user_id: "user-1",
    title: "AI Sneaker Ad — 15s Spot",
    description: "AI sportswear ad reference for agency work",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    source_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["veo", "runway"],
    genre: "ad",
    prompt: "dynamic product shot, sneaker floating, studio lighting, slow motion",
    likes_count: 612,
    views_count: 4100,
    downloads_count: 98,
    is_nsfw: false,
    created_at: "2026-05-18T16:00:00Z",
  },
  {
    id: "vid-5",
    user_id: "user-2",
    title: "Abstract Dreams — Experimental",
    description: "Experimental video with Grok + Hailuo",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    source_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["grok", "hailuo"],
    genre: "experimental",
    prompt: "surreal morphing shapes, dreamlike colors, non-linear narrative",
    likes_count: 489,
    views_count: 2750,
    downloads_count: 67,
    is_nsfw: false,
    created_at: "2026-05-20T11:00:00Z",
  },
  {
    id: "vid-6",
    user_id: "user-3",
    title: "Pixel Forest Animation",
    description: "PixVerse animation short form",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    source_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    platform: "youtube",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    ai_tools: ["pixverse"],
    genre: "animation",
    prompt: "pixel art forest, fireflies, gentle wind animation",
    likes_count: 334,
    views_count: 1920,
    downloads_count: 41,
    is_nsfw: false,
    created_at: "2026-05-21T08:00:00Z",
  },
];

export const mockComments: Comment[] = [
  {
    id: "comment-1",
    video_id: "vid-1",
    user_id: "user-2",
    content: "The Kling motion on the rain loop is incredibly smooth.",
    created_at: "2026-05-19T10:00:00Z",
  },
  {
    id: "comment-2",
    video_id: "vid-1",
    user_id: "user-3",
    content: "Would love the Suno prompt breakdown if you can share it.",
    created_at: "2026-05-19T12:30:00Z",
  },
];

export const mockChallenges: Challenge[] = [
  {
    id: "challenge-1",
    title: "30-Second Kling Short Film",
    description: "Create a narrative short under 30 seconds using Kling 2.0.",
    tool: "kling",
    prize: "Featured on homepage",
    ends_at: "2026-06-15T00:00:00Z",
    entries_count: 24,
    status: "active",
  },
  {
    id: "challenge-2",
    title: "Runway Loop Challenge",
    description: "Build a seamless ambient loop with Runway Gen-3.",
    tool: "runway",
    prize: "Creator spotlight badge",
    ends_at: "2026-06-01T00:00:00Z",
    entries_count: 17,
    status: "active",
  },
  {
    id: "challenge-3",
    title: "Suno Music Video Jam",
    description: "Pair Suno audio with any AI video tool of your choice.",
    tool: "suno",
    prize: "Community vote winner",
    ends_at: "2026-07-01T00:00:00Z",
    entries_count: 0,
    status: "upcoming",
  },
];

export function attachUsersToVideos(videos: Video[], users: User[]): Video[] {
  const userMap = new Map(users.map((u) => [u.id, u]));
  return videos.map((v) => ({ ...v, user: userMap.get(v.user_id) }));
}
